export const mockUser = {
  id: 'user_1',
  name: 'Alex Developer',
  email: 'alex@example.com',
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: 'type_snippet', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
  { id: 'type_prompt', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
  { id: 'type_command', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
  { id: 'type_note', name: 'note', icon: 'StickyNote', color: '#fde047', isSystem: true },
  { id: 'type_file', name: 'file', icon: 'File', color: '#6b7280', isSystem: true },
  { id: 'type_image', name: 'image', icon: 'Image', color: '#ec4899', isSystem: true },
  { id: 'type_link', name: 'link', icon: 'Link', color: '#10b981', isSystem: true },
];

export const mockCollections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Common React patterns and best practices',
    isFavorite: true,
    itemCount: 1,
  },
  {
    id: 'col_2',
    name: 'Context Files',
    description: 'AI context and instruction files',
    isFavorite: false,
    itemCount: 1,
  },
  {
    id: 'col_3',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: true,
    itemCount: 1,
  },
  {
    id: 'col_4',
    name: 'Terminal Commands',
    description: 'Frequently used CLI commands',
    isFavorite: false,
    itemCount: 0,
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useDebounce Hook',
    contentType: 'TEXT' as const,
    content: `function useDebounce(value, delay) {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => {\n    const handler = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(handler);\n  }, [value, delay]);\n  return debounced;\n}`,
    description: 'Custom React hook for debouncing values',
    isFavorite: false,
    isPinned: false,
    language: 'javascript',
    tags: ['react', 'hooks'],
    itemTypeId: 'type_snippet',
    itemType: { id: 'type_snippet', name: 'snippet', icon: 'Code', color: '#3b82f6' },
    collectionIds: ['col_1'],
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-04-20T10:00:00Z',
  },
  {
    id: 'item_2',
    title: 'Code Review Prompt',
    contentType: 'TEXT' as const,
    content: `You are a senior software engineer. Review the following code for:\n1. Potential bugs or errors\n2. Performance issues\n3. Security vulnerabilities\n\nProvide specific, actionable feedback.`,
    description: 'AI prompt for comprehensive code reviews',
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ['ai', 'code-review'],
    itemTypeId: 'type_prompt',
    itemType: { id: 'type_prompt', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6' },
    collectionIds: [],
    createdAt: '2026-04-19T14:00:00Z',
    updatedAt: '2026-04-19T14:00:00Z',
  },
  {
    id: 'item_3',
    title: 'Git Rebase Notes',
    contentType: 'TEXT' as const,
    content: `Quick reference for git interactive rebase:\n\ngit rebase -i HEAD~3\n\nCommands:\n- pick: use commit\n- reword: edit message\n- squash: merge into previous`,
    description: 'Quick reference for git interactive rebase',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['git'],
    itemTypeId: 'type_note',
    itemType: { id: 'type_note', name: 'note', icon: 'StickyNote', color: '#fde047' },
    collectionIds: [],
    createdAt: '2026-04-18T09:00:00Z',
    updatedAt: '2026-04-18T09:00:00Z',
  },
  {
    id: 'item_4',
    title: 'Docker Cleanup',
    contentType: 'TEXT' as const,
    content: `docker system prune --volumes`,
    description: 'Remove all unused Docker resources',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    tags: ['docker', 'cleanup'],
    itemTypeId: 'type_command',
    itemType: { id: 'type_command', name: 'command', icon: 'Terminal', color: '#f97316' },
    collectionIds: ['col_4'],
    createdAt: '2026-04-17T11:00:00Z',
    updatedAt: '2026-04-17T11:00:00Z',
  },
  {
    id: 'item_5',
    title: 'Python List Comprehension',
    contentType: 'TEXT' as const,
    content: `# Basic list comprehension\nsquares = [x**2 for x in range(10)]\n\n# With condition\nevens = [x for x in range(20) if x % 2 == 0]`,
    description: 'Common list comprehension examples',
    isFavorite: false,
    isPinned: false,
    language: 'python',
    tags: ['python', 'basics'],
    itemTypeId: 'type_snippet',
    itemType: { id: 'type_snippet', name: 'snippet', icon: 'Code', color: '#3b82f6' },
    collectionIds: ['col_3'],
    createdAt: '2026-04-16T15:00:00Z',
    updatedAt: '2026-04-16T15:00:00Z',
  },
  {
    id: 'item_6',
    title: 'API Documentation Template',
    contentType: 'TEXT' as const,
    content: `## Endpoint Name\n\n**Method:** GET  \n**Path:** /api/resource/:id\n\n### Parameters\n| Name | Type | Required | Description |\n|------|------|----------|-------------|\n| id | string | Yes | Resource ID |`,
    description: 'Template for documenting REST API endpoints',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['api', 'documentation'],
    itemTypeId: 'type_note',
    itemType: { id: 'type_note', name: 'note', icon: 'StickyNote', color: '#fde047' },
    collectionIds: [],
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-04-15T08:00:00Z',
  },
  {
    id: 'item_7',
    title: 'Vercel Docs',
    contentType: 'URL' as const,
    content: null,
    url: 'https://vercel.com/docs',
    description: 'Official Vercel documentation',
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ['vercel', 'docs'],
    itemTypeId: 'type_link',
    itemType: { id: 'type_link', name: 'link', icon: 'Link', color: '#10b981' },
    collectionIds: [],
    createdAt: '2026-04-14T12:00:00Z',
    updatedAt: '2026-04-14T12:00:00Z',
  },
  {
    id: 'item_8',
    title: 'Kill Process on Port',
    contentType: 'TEXT' as const,
    content: `lsof -ti:3000 | xargs kill -9`,
    description: 'Kill any process running on port 3000',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    tags: ['terminal', 'node'],
    itemTypeId: 'type_command',
    itemType: { id: 'type_command', name: 'command', icon: 'Terminal', color: '#f97316' },
    collectionIds: ['col_4'],
    createdAt: '2026-04-13T16:00:00Z',
    updatedAt: '2026-04-13T16:00:00Z',
  },
];
